spring:
  r2dbc:
    url: r2dbc:h2:mem:////test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  logging:
    level:
      io:
        r2dbc:
          h2: TRACE
      org:
        springframework:
          r2dbc: DEBUG
  debug: true

jwt:
  secret: YXZhdGFydHJpcGF1dGhvcml6YXRpb25qd3RtYW5hZ2VzZWNyZXRrZXkK
  expired-in: 600000 # 10 min
  refresh-expired-in: 86400000 # 24 hour
