SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE challenge;
ALTER TABLE challenge ALTER COLUMN ID RESTART WITH 1;
TRUNCATE TABLE daily;
ALTER TABLE daily ALTER COLUMN ID RESTART WITH 1;
TRUNCATE TABLE users;
ALTER TABLE users ALTER COLUMN ID RESTART WITH 1;
SET REFERENTIAL_INTEGRITY TRUE